services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: hono-todo-postgres-betterauth
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=hono-todo-betterauth
